### ISSUE TITLE
not working in android 4.0 and the lock dosent work after few menints !!

### ISSUE THREAD

**Issue by MohebYasser** [lizixian18/temporary#4]
hi
what minimum sdk the app work with?
the lock dosent work after i celled all aps or after few minuts !!
can you fix it and make the lock work normaly?   thanks

**Comment by EspoirX** [comment]
Ok，let me check。

**Comment by EspoirX** [comment]
This place is wrong：
Intent intent = new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS);
startActivityForResult(intent, RESULT_ACTION_USAGE_ACCESS_SETTINGS);

because I forgot to add the version to judge.
