### ISSUE TITLE
这个应用5.0以下的手机是不是用不了

### ISSUE THREAD

**Issue by 1360306918** [lizixian18/temporary#5]

**Comment by lizixian18** [comment]
没试过哦，不过这些东西自己配置一下就好，这项目主要是提供一种实现的思路，其实代码还是很多地方需要优化的。

**Comment by EspoirX** [comment]
是不是这个地方报错： 
Intent intent = new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS);
startActivityForResult(intent, RESULT_ACTION_USAGE_ACCESS_SETTINGS);

我看了一下，Settings.ACTION_USAGE_ACCESS_SETTINGS是有版本限制的，忘记加判断了，我加一下
